version: "3.3"
services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=umuzi_db
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
      - ./src:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080